name: Deploy on Google App Engine

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - id: 'setup-gcloud'
      name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'
    - id: 'deploy'
      name: 'Deploying to Google Cloud App Engine'
      run: 'make deploy'
      env:
        SUPABASE_URL: '${{ secrets.SUPABASE_URL }}'
        SUPABASE_KEY: '${{ secrets.SUPABASE_KEY }}'
        OPENAI_API_KEY: '${{ secrets.OPENAI_API_KEY }}'
        OPENAI_ORGANIZATION: '${{ secrets.OPENAI_ORGANIZATION }}'
        OPENAI_MODEL: '${{ vars.OPENAI_MODEL }}'
        JWT_SECRET: '${{ secrets.JWT_SECRET }}'
